spring:
  application:
    name: ghost-drop

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none # or create, create-drop, validate, none
      show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
#    locations: classpath:db/migration

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB

file:
  upload-dir: uploads/

server:
  address: 0.0.0.0
  port: 5767

app:
  base-url: http://localhost:5767

error-docs:
  url: http://fruitloop.local:5768/errors